<?php

namespace frontend\models;
use yii\db\ActiveRecord;

class person2 extends ActiveRecord
{
    public static function tableName()
        {
            return 'person';
        }

        public function rules()
        {
            return [
                [['firstname'], 'string' ],
                [['gender'], 'string' ],
                [['firstname', 'gender'], 'required' ],
            ];
        }

    public function beforeSave($insert)
    {
        $this->firstname = 'sanjar';
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterFind()
    {
        $this->firstname = 'salom';
        parent::afterFind(); // TODO: Change the autogenerated stub
        parent::afterFind();
    }


}
